version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mysql:8.3.0
    environment:
    - MYSQL_DATABASE=${DB_DATABASE}
    - MYSQL_HOST=${DB_HOST}
    - MYSQL_USER=${DB_USER}         
    - MYSQL_PASSWORD=${DB_PASSWORD} 
    - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", "${SESSION_PASSWORD}"]
    environment:
    - SESSION_PASSWORD=${SESSION_PASSWORD} 
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
